version: '3.8'

services:
  backend:
    build: ./server
    container_name: backend-container
    ports:
      - "3000:3000"
    environment:
      - DB_URL=tu_url_de_render  # Tu conexión a la BD en la nube
    networks:
      - app-network

  frontend:
    build: .
    container_name: frontend-container
    ports:
      - "80:80"  # Nginx servirá en el puerto 80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge